name: sada_checkpoint
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sada_design_system:
    path: ../../packages/sada_design_system
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.4.1
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  mask_text_input_formatter: ^2.9.0
  camera: ^0.11.3
  path_provider: ^2.1.5
  path: ^1.9.1
  signature: ^6.3.0
  flutter_svg: ^2.2.2
  database:
    path: ../../packages/database
  http_service:
    path: ../../packages/http_service
  intl: ^0.20.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
